### Loading data : Economic Sanctions Reconsidered, Third Edition: Databasea

In [201]:
#Required libraries
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [202]:
pwd

'C:\\Users\\Formation\\Desktop\\Remote working\\Remote training\\S18'

In [203]:
# Loading data
data_table =  pd.read_excel("./data/DATABASE.xls", header=3, nrows=204)

# Taking a look at head
data_table.head()

,Case no.b,Sender c,Sender 2c,Sender 3c,Targetd,Goal,US casee,US unilateral casef,Foreign policy goal categoryg,First yearh,...,Cost to target per capitabb,Trade linkagecc,GNP \nratiodd,Health and stabilityee,Sanction typeff,Cost to sendergg,"GDP growth (percent, 5-year average)hh","Inflation (percent,\n 3-year average)ii",Target International Monetary Fund codejj,Country groupkk
0,14-1,UNITED KINGDOM,NaN,NaN,GERMANY,Military victory,0,0,4,1914,...,12.58,9,1.0,3,"F,X,M",4,3.58,2.86667,134,1
1,17-1,UNITED STATES,NaN,NaN,JAPAN,Shipping for Allies,1,1,5,1917,...,0.44,20.5,13.0,3,X,2,5.4,25.6,158,1
2,18-1,UNITED KINGDOM,NaN,NaN,RUSSIA,Destabilize Bolsheviks,0,0,2,1918,...,2.49,18.5,1.0,1,"F,X,M",3,n.a.,n.a.,922,2
3,21-1,LEAGUE OF NATIONS,NaN,NaN,YUGOSLAVIA,Military disruption vs. Albania,0,0,3,1921,...,--,26.5,37.0,2,--,2,-1.5,n.a.,188,2
4,25-1,LEAGUE OF NATIONS,NaN,NaN,GREECE,Withdraw from Bulgaria,0,0,3,1925,...,--,36,56.0,2,--,2,3.3,48.8,174,1

In [204]:
# Removing last characters of column names (removing exponents)
cols = list(data_table.columns)

for i in range(39):
    if(i > 25):
        cols[i] = cols[i][:-2]
    
    else:
        cols[i] = cols[i][:-1]
        
# Replacing column names of the dataframe
col_rename_dict = {i:j for i,j in zip(list(data_table.columns), cols)}
data_table.rename(columns=col_rename_dict, inplace=True)

# Handling exception renaming
data_table.rename(columns={"Goa":"Goal"})

,Case no.,Sender,Sender 2,Sender 3,Target,Goal,US case,US unilateral case,Foreign policy goal category,First year,...,Cost to target per capita,Trade linkage,GNP \nratio,Health and stability,Sanction type,Cost to sender,"GDP growth (percent, 5-year average)","Inflation (percent,\n 3-year average)",Target International Monetary Fund code,Country group
0,14-1,UNITED KINGDOM,NaN,NaN,GERMANY,Military victory,0,0,4,1914,...,12.58,9,1.00,3,"F,X,M",4,3.58,2.86667,134,1
1,17-1,UNITED STATES,NaN,NaN,JAPAN,Shipping for Allies,1,1,5,1917,...,0.44,20.5,13.00,3,X,2,5.4,25.6,158,1
2,18-1,UNITED KINGDOM,NaN,NaN,RUSSIA,Destabilize Bolsheviks,0,0,2,1918,...,2.49,18.5,1.00,1,"F,X,M",3,n.a.,n.a.,922,2
3,21-1,LEAGUE OF NATIONS,NaN,NaN,YUGOSLAVIA,Military disruption vs. Albania,0,0,3,1921,...,--,26.5,37.00,2,--,2,-1.5,n.a.,188,2
4,25-1,LEAGUE OF NATIONS,NaN,NaN,GREECE,Withdraw from Bulgaria,0,0,3,1925,...,--,36,56.00,2,--,2,3.3,48.8,174,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,98-3,TURKEY,NaN,NaN,ITALY,Kurdish leader,0,0,1,1998,...,--,1.4,0.16,3,--,2,1.46,3.73333,136,1
200,99-1,UNITED NATIONS,UNITED STATES,NaN,AFGHANISTAN,Extradite Osama bin Laden,1,0,1,1999,...,1.67,100,5939.00,1,"F,X,M",2,8.23957,n.a.,512,5
201,99-2,UNITED STATES,EUROPEAN UNION,FRANCE,IVORY COAST,"Coup, democracy",1,0,2,1999,...,2.5,54,1408.00,1,F,1,5.22,3.73333,662,6
202,99-3,UNITED STATES,JAPAN,NaN,PAKISTAN,"Coup, democracy",1,0,2,1999,...,0.001,20,232.00,1,F,1,3.42,9.33333,564,5
203,00-1,UNITED STATES,NaN,NaN,ECUADOR,Coup,1,0,2,2000,...,--,34,614.00,1,--,2,0.82,39.6333,248,3

In [246]:
# Sanity check to see if there is a column with all NaN values inside
for c in data_table.columns:
    if(data_table[c].isna().sum() == 204):
        print(c)

#### Preprocessing textual data

In [206]:
data_table.columns

Index(['Case no.', 'Sender ', 'Sender 2', 'Sender 3', 'Target', 'Goa',
       'US case', 'US unilateral case', 'Foreign policy goal category',
       'First year', 'Last year', 'Policy result', 'Sanctions contribution',
       'Success \nscore', 'Companion policies', 'International cooperation',
       'International assistance', 'Cooperating international organization',
       'International organization sender',
       'International organization sender & target members', 'Length (years)',
       'Prior relations', 'Regime Type \n(DEMOC 1st year)',
       'Regime Type2 (Polity2 1st year)', 'Regime Type3 \n(Scale 1st year)',
       'Political stability prior', 'Political stability durin',
       'Cost to targe', 'Cost to target (percent of GNP)',
       'Cost to target per capita', 'Trade linkage', 'GNP \nratio',
       'Health and stability', 'Sanction type', 'Cost to sender',
       'GDP growth (percent, 5-year average)',
       'Inflation (percent,\n 3-year average)',
       'Target International Monetary Fund code', 'Country group'],
      dtype='object')

In [207]:
# Defininf X as all variables different from 'Success score', 'Policy result' and 'sanction contriution' and dropping 
# the last two asthey are correlated with the first one.

data_table = data_table.drop(['Policy result', 'Sanctions contribution'], axis=1)

# Copying 'Success \nscore' column then dropping the first (to have it as last column)
data_table['Success score'] = data_table['Success \nscore']
data_table = data_table.drop(['Success \nscore'], axis=1)

In [208]:
data_table.dtypes

Case no.                                               object
Sender                                                 object
Sender 2                                               object
Sender 3                                               object
Target                                                 object
Goa                                                    object
US case                                                 int64
US unilateral case                                      int64
Foreign policy goal category                            int64
First year                                              int64
Last year                                              object
Companion policies                                     object
International cooperation                               int64
International assistance                               object
Cooperating international organization                 object
International organization sender                       int64
International organization sender & target members      int64
Length (years)                                          int64
Prior relations                                         int64
Regime Type \n(DEMOC 1st year)                         object
Regime Type2 (Polity2 1st year)                        object
Regime Type3 \n(Scale 1st year)                        object
Political stability prior                              object
Political stability durin                              object
Cost to targe                                          object
Cost to target (percent of GNP)                        object
Cost to target per capita                              object
Trade linkage                                          object
GNP \nratio                                           float64
Health and stability                                    int64
Sanction type                                          object
Cost to sender                                          int64
GDP growth (percent, 5-year average)                   object
Inflation (percent,\n 3-year average)                  object
Target International Monetary Fund code                object
Country group                                           int64
Success score                                           int64
dtype: object

In [231]:
data_table.head()

,Case no.,Sender,Sender 2,Sender 3,Target,Goa,US case,US unilateral case,Foreign policy goal category,First year,...,Trade linkage,GNP \nratio,Health and stability,Sanction type,Cost to sender,"GDP growth (percent, 5-year average)","Inflation (percent,\n 3-year average)",Target International Monetary Fund code,Country group,Success score
0,14-1,UNITED KINGDOM,NaN,NaN,GERMANY,Military victory,0,0,4,1914,...,9,1.0,3,"F,X,M",4,3.58,2.86667,134,1,12
1,17-1,UNITED STATES,NaN,NaN,JAPAN,Shipping for Allies,1,1,5,1917,...,20.5,13.0,3,X,2,5.4,25.6,158,1,4
2,18-1,UNITED KINGDOM,NaN,NaN,RUSSIA,Destabilize Bolsheviks,0,0,2,1918,...,18.5,1.0,1,"F,X,M",3,n.a.,n.a.,922,2,2
3,21-1,LEAGUE OF NATIONS,NaN,NaN,YUGOSLAVIA,Military disruption vs. Albania,0,0,3,1921,...,26.5,37.0,2,--,2,-1.5,n.a.,188,2,16
4,25-1,LEAGUE OF NATIONS,NaN,NaN,GREECE,Withdraw from Bulgaria,0,0,3,1925,...,36,56.0,2,--,2,3.3,48.8,174,1,16

In [245]:
# Checking the length of a column with unique values
len(data_table['Sender '].unique())

data_table['Sender '].head()

0       UNITED KINGDOM
1        UNITED STATES
2       UNITED KINGDOM
3    LEAGUE OF NATIONS
4    LEAGUE OF NATIONS
Name: Sender , dtype: object

#### Training part with NN

In [226]:
X, y = data_table.iloc[:,2:36], data_table.iloc[:,:37] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [227]:
mlp = MLPClassifier(random_state=42)
mlp.fit(X_train, y_train)

print("Accuracy on training set : {:.2f}".format(mlp.score(X_train, y_train)))
print("Accuracy on test set : {:.2f}".format(mlp.score(X_test, y_test)))

ValueError: could not convert string to float: 'SPAIN'